version: '3.8'

services:
  app:
    container_name: 'test-app'
    build:
      context: '.'
    ports:
      - ${PORT}:${PORT}
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@test-db:5432/${DB_USER}
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    restart: 'unless-stopped'
    command: bash -c "npm run prisma:init && npm run test"
    depends_on:
      - 'db'

  db:
    container_name: 'test-db'
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    expose:
      - 5432
