version: '3.8'

services:
  app:
    container_name: 'dev-app'
    build:
      context: '.'
    ports:
      - ${PORT}:${PORT}
    environment:
      - NODE_ENV=development
      - PORT=${PORT}
      - SALT_ROUNDS=${SALT_ROUNDS}
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@dev-db:5432/${DB_USER}
      - ACCESS_TOKEN_EXPIRES_TIME=${ACCESS_TOKEN_EXPIRES_TIME}
      - REFRESH_TOKEN_EXPIRES_TIME=${REFRESH_TOKEN_EXPIRES_TIME}
      - GOOGLE_OAUTH_CLIENT_ID=${GOOGLE_OAUTH_CLIENT_ID}
      - GOOGLE_OAUTH_CLIENT_SECRET=${GOOGLE_OAUTH_CLIENT_SECRET}
      - GOOGLE_OAUTH_REDIRECT_URI=${GOOGLE_OAUTH_REDIRECT_URI}
      - WEB_APP_URL=${WEB_APP_URL}
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    restart: 'unless-stopped'
    command: bash -c "npx pnpm prisma:generate && npx prisma migrate deploy && npx pnpm dev"
    depends_on:
      - 'db'

  db:
    container_name: 'dev-db'
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    expose:
      - 5432
    volumes:
      - 'data-development:/var/lib/postgresql/data'

volumes:
  data-development:
