version: '3.8'

services:
  app:
    container_name: 'dev-app'
    build:
      context: '.'
    ports:
      - ${PORT}:${PORT}
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@dev-db:5432/${DB_USER}
    env_file: .env.development
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    restart: 'unless-stopped'
    command: bash -c "npx pnpm prisma:init && npx pnpm dev"
    depends_on:
      - 'db'

  db:
    container_name: 'dev-db'
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    expose:
      - 5432
    volumes:
      - 'data-development:/var/lib/postgresql/data'

volumes:
  data-development:
