version: '3.8'

services:
  app:
    container_name: 'app'
    build:
      context: '.'
    ports:
      - ${PORT}:${PORT}
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - SALT_ROUNDS=${SALT_ROUNDS}
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db:5432/postgres
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    restart: 'unless-stopped'
    command: bash -c "npx pnpm prisma:generate || npx pnpm prisma:migrate:dev || ${DOCKER_COMMAND}"
    depends_on:
      - 'db'

  db:
    container_name: 'db'
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - 'data:/var/lib/postgresql/data'

volumes:
  data:
