version: '3.8'

services:
  app:
    container_name: 'prod-app'
    build:
      context: '.'
    ports:
      - ${PORT}:${PORT}
    restart: 'unless-stopped'
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
      - SALT_ROUNDS=${SALT_ROUNDS}
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@prod-db:5432/${DB_USER}
    command: bash -c "npx pnpm prisma:generate && npx prisma migrate deploy && npx pnpm prod"
    depends_on:
      - 'db'

  db:
    container_name: 'prod-db'
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - 'data-production:/var/lib/postgresql/data'
    expose:
      - 5432

volumes:
  data-production:
